import React, { useMemo, useRef, useEffect } from 'react';
import type { PipelineResult, Mutation } from '../types';

interface Props {
  result: PipelineResult | null;
  selectedSpike: number | null;
}

function MutationRow({ m }: { m: Mutation }) {
  return (
    <tr className={m.region === 'VR_VIII' ? 'row-viii' : 'row-iv'}>
      <td><span className={`region-chip ${m.region === 'VR_VIII' ? 'viii' : 'iv'}`}>{m.region.replace('_', '-')}</span></td>
      <td className="mono">{m.positionVp1}</td>
      <td className="mono">
        <span className="aa-old">{m.original}</span>
        <span className="arrow">→</span>
        <span className={`aa-new ${m.chargeAfter > 0 ? 'pos' : m.chargeAfter < 0 ? 'neg' : ''}`}>{m.mutated}</span>
      </td>
      <td>
        {m.chargeReversal && <span className="flag reversal">charge flip</span>}
        {m.isEpitope && <span className="flag epitope">NAb epitope</span>}
      </td>
    </tr>
  );
}

export default function SequenceOutputPanel({ result, selectedSpike }: Props) {
  const seqRef = useRef<HTMLDivElement>(null);

  const mutationMap = useMemo(() => {
    const map = new Map<number, Mutation>();
    if (result) for (const m of result.mutations) map.set(m.position - 1, m);
    return map;
  }, [result]);

  const chars = useMemo(() => {
    if (!result) return [] as React.ReactNode[];
    const out: React.ReactNode[] = [];
    for (let i = 0; i < result.sequence.length; i++) {
      const m = mutationMap.get(i);
      if (m) {
        const cls = m.chargeAfter > 0 ? 'pos' : m.chargeAfter < 0 ? 'neg' : 'neu';
        out.push(
          <span key={i} className={`res mut ${cls} ${m.region === 'VR_VIII' ? 'viii' : 'iv'}`} title={`VP1 ${m.positionVp1}: ${m.original}→${m.mutated}`}>
            {result.sequence[i]}
          </span>
        );
      } else {
        out.push(<span key={i} className="res">{result.sequence[i]}</span>);
      }
    }
    return out;
  }, [result, mutationMap]);

  useEffect(() => {
    if (selectedSpike !== null && seqRef.current) {
      const el = seqRef.current.querySelector('.res.mut');
      if (el) el.scrollIntoView({ behavior: 'smooth', block: 'center' });
    }
  }, [selectedSpike]);

  if (!result) {
    return (
      <div className="seq-panel">
        <div className="panel-title">📄 Engineered Capsid Output</div>
        <div className="seq-empty">
          Read-only. The optimized VP1 sequence is generated by the backend
          <code> aav_generator.py</code> + <code>epitope_masker.py</code> loops — run the pipeline to populate it.
        </div>
      </div>
    );
  }

  const s = result.scores;

  return (
    <div className="seq-panel">
      <div className="panel-title">📄 Engineered Capsid #{result.candidateId} <span className="readonly-badge">READ-ONLY OUTPUT</span></div>

      <div className="score-grid">
        <div className="score-cell"><span>Cardiac tropism</span><strong>{((s?.cardiacTropism ?? 0) * 100).toFixed(0)}%</strong></div>
        <div className="score-cell"><span>Hepatic avoidance</span><strong>{((s?.hepaticAvoidance ?? 0) * 100).toFixed(0)}%</strong></div>
        <div className="score-cell"><span>Immune evasion</span><strong>{((s?.immuneEvasion ?? 0) * 100).toFixed(0)}%</strong></div>
        <div className="score-cell"><span>LAMP2B compat.</span><strong>{((s?.lamp2bExpression ?? 0) * 100).toFixed(0)}%</strong></div>
        <div className="score-cell accent"><span>Immune escape vs UCL</span><strong>{(s?.improvementVsUcl ?? 0).toFixed(1)}×</strong></div>
        <div className="score-cell"><span>Docking preserved</span><strong>{s?.dockingPreserved ? '✓ yes' : '✗ no'}</strong></div>
      </div>

      <div className="seq-meta">
        <span>VP1 residues {result.vpOffset}–{result.vpOffset + result.sequence.length - 1}</span>
        <span>{result.mutations.length} substitutions</span>
        <span>{result.poolEvaluated.toLocaleString()} variants evaluated</span>
      </div>

      <div className="seq-block" ref={seqRef}>{chars}</div>

      <div className="mut-table-wrap">
        <table className="mut-table">
          <thead><tr><th>Region</th><th>VP1 pos</th><th>Substitution</th><th>Property</th></tr></thead>
          <tbody>
            {result.mutations.map((m, i) => <MutationRow key={i} m={m} />)}
          </tbody>
        </table>
      </div>
    </div>
  );
}
